name: simple_utils_flutter
description: A package to simplify your coding. Using Shared preferences, Firestore Database, File and image picker made easy by simplifying them. Now You can use these methods my adding a single line.
version: 0.0.3
repository: https://github.com/harshitAmar/simple_utils_flutter.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.4.5
  file_picker: ^5.2.10
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

 
flutter:

  